[package]
name = "helper"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
regex = "1.11.3"
serde = {version = "1.0.221", features = ["derive"]}
tera = "1.20.0"
tokio = "1.47.1"
toml = "0.9.5"
